event-per-day: 3
event-hour-range: 13-23
debug-event-hour: 03:00

messages:
  start-event: |-
    &f
    &f &c&lNUOVA QUEST GLOBALE
    &f %name%
    &f
  expired-quest:  |-
    &f
    &f &c&lQUEST GLOBALE TERMINATA
    &f Non avete &cfinito&f in tempo!
    &f
  end-quest:  |-
    &f
    &f &c&lQUEST GLOBALE TERMINATA
    &f &FColoro che hanno &ccontribuito
    &f &Falmeno con &c%percentage%% &friceveranno
    &f &le ricompense!
    &f 
    &f La tua percentuale&8: &c%player_percentage%&8% 
    &f
    

rewards-winner:
  0:
    - "cc give p RubyCrate 5 %player%"
    - "amc give %player% CropsPouch 2"
    - "event economy give cioccolato %player% 25000 --ignoreEvent"
    - "amc give %player% Seasonal14"
    - "crops virtual give %player% 250"
  1:
    - "cc give p RubyCrate 5 %player%"
    - "amc give %player% CropsPouch 2"
    - "event economy give cioccolato %player% 25000 --ignoreEvent"
    - "crops virtual give %player% 250"
    - "[5] cc give p RubyCrate 3 %player%"
    - "[5] amc give %player% CropsPouch 1"
    - "[5] crops virtual give %player% 100"

rewards-loser:
  0:
    - "cc give p RubyCrate 1 %player%"
    - "event economy give cioccolato %player% 5000 --ignoreEvent"
    - "crops virtual give %player% 100"
  1:
    - "cc give p RubyCrate 1 %player%"
    - "event economy give cioccolato %player% 5000 --ignoreEvent"
    - "crops virtual give %player% 100"
    - "[5] cc give p RubyCrate 1 %player%"
    - "[5] amc give %player% CropsPouch 1"